version: '3.2'

services:

  mysql: # Mysql container
    container_name: development-mysql
    image: mysql:5.7
    restart: always
    volumes:
      - ./conf:/etc/mysql/conf.d
      - ./logs:/var/log/mysql
      - ./init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todo
      MYSQL_USER:     todo
      MYSQL_PASSWORD: todo
      TZ: Asia/Tokyo
    ports:
      - 3306:3306
