// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"fmt"
	"io"
	"strconv"
)

type Todo struct {
	ID     int        `json:"id"`
	UserID int        `json:"user_id"`
	Name   string     `json:"name"`
	Status TodoStatus `json:"status"`
}

type TodoWithoutID struct {
	UserID int        `json:"user_id"`
	Name   string     `json:"name"`
	Status TodoStatus `json:"status"`
}

type User struct {
	ID   int    `json:"id"`
	Name string `json:"name"`
}

type TodoStatus string

const (
	TodoStatusNotYet TodoStatus = "NOT_YET"
	TodoStatusDone   TodoStatus = "DONE"
)

var AllTodoStatus = []TodoStatus{
	TodoStatusNotYet,
	TodoStatusDone,
}

func (e TodoStatus) IsValid() bool {
	switch e {
	case TodoStatusNotYet, TodoStatusDone:
		return true
	}
	return false
}

func (e TodoStatus) String() string {
	return string(e)
}

func (e *TodoStatus) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = TodoStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid TodoStatus", str)
	}
	return nil
}

func (e TodoStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}
